<?php
    include('include/header.php');
    include('include/alertes.php');
    include('include/import_lecon.php');
    include('include/add_lecon.php');
    include('include/add_theme.php');
    include('include/add_user.php');
    include('include/update_lecon.php');
    include('include/update_theme.php');
    include('include/update_user.php');
    include('include/update_account.php');
?>